export const gregorianConfigsPortuguese = {
  dayNames: [
    "Domingo",
    "Segunda",
    "Terça",
    "Quarta",
    "Quinta",
    "Sexta",
    "Sábado",
  ],
  dayNamesShort: ["Dom", "Seg", "Ter", "Qua", "Qui", "Sex", "Sáb"],
  monthNames: [
    "Janeiro",
    "Fevereiro",
    "Março",
    "Abril",
    "Maio",
    "Junho",
    "Julho",
    "Agosto",
    "Setembro",
    "Outubro",
    "Novembro",
    "Dezembro",
  ],
  selectedFormat: "YYYY/MM/DD",
  dateFormat: "YYYY/MM/DD",
  monthYearFormat: "YYYY MM",
  timeFormat: "HH:mm",
  hour: "Hora",
  minute: "Minuto",
  timeSelect: "Selecione",
  timeClose: "Fechar",
};
